Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 12.00.8804 for 80x86
Copyright (C) Microsoft Corp 1984-1998. All rights reserved.

decl1.c
decl1.c(5) : warning: Declaration does not declare anything
decl1.c(8) : error: Invalid storage class in file scope
decl1.c(10) : error: Invalid storage class in file scope
decl1.c(14) : error: 'g3': already declared in this scope
     decl1.c(13) : See previous declaration of 'g3'
decl1.c(17) : error: 'g4' already declared with a different storage class
     decl1.c(16) : See previous declaration of 'g4'
decl1.c(21) : error: 'g5': already declared in this scope
     decl1.c(20) : See previous declaration of 'g5'
decl1.c(24) : error: 'f1': already declared in this scope
     decl1.c(23) : See previous declaration of 'f1'
decl1.c(28) : error: 'g6': already declared in this scope
     decl1.c(27) : See previous declaration of 'g6'
decl1.c(31) : error: 'g7' already declared with a different storage class
     decl1.c(30) : See previous declaration of 'g7'
decl1.c(34) : error: 'g8' already declared with a different storage class
     decl1.c(33) : See previous declaration of 'g8'
decl1.c(37) : error: 'f2' already declared with a different storage class
     decl1.c(36) : See previous declaration of 'f2'
decl1.c(40) : error: 'f3' already declared with a different storage class
     decl1.c(39) : See previous declaration of 'f3'
decl1.c(44) : warning: 'g9': already declared in this scope
     decl1.c(43) : See previous declaration of 'g9'
decl1.c(47) : error: 'g10': already declared in this scope
     decl1.c(46) : See previous declaration of 'g10'
decl1.c(50) : error: 'g11': already declared in this scope
     decl1.c(49) : See previous declaration of 'g11'
decl1.c(52) : error: 'f2': already declared in this scope
     decl1.c(36) : See previous declaration of 'f2'
decl1.c(55) : error: 'g12': already declared in this scope
     decl1.c(54) : See previous declaration of 'g12'
decl1.c(63) : error: A block-scope function may only have extern storage
decl1.c(64) : error: A block-scope function may only have extern storage
decl1.c(65) : error: A block-scope function may only have extern storage
decl1.c(68) : error: 'l1': already declared in this scope
     decl1.c(67) : See previous declaration of 'l1'
decl1.c(69) : error: 'l1': already declared in this scope
     decl1.c(67) : See previous declaration of 'l1'
decl1.c(70) : error: 'l1': already declared in this scope
     decl1.c(67) : See previous declaration of 'l1'
decl1.c(71) : error: 'l1': already declared in this scope
     decl1.c(67) : See previous declaration of 'l1'
decl1.c(74) : error: 'l2': already declared in this scope
     decl1.c(73) : See previous declaration of 'l2'
decl1.c(80) : error: 'l5': already declared in this scope
     decl1.c(79) : See previous declaration of 'l5'
decl1.c(82) : warning: Declaration does not declare anything
decl1.c(88) : error: 'p1': Invalid parameter storage class
decl1.c(89) : error: 'p2': Invalid parameter storage class
decl1.c(90) : error: 'p3': Invalid parameter storage class
decl1.c(91) : error: 'p4': Invalid parameter storage class
decl1.c(96) : error: 'p6': already declared in this scope
     decl1.c(94) : See previous declaration of 'p6'
decl1.c(97) : error: 'p5': already declared in this scope
     decl1.c(93) : See previous declaration of 'p5'
decl1.c(107) : error: 'func3': function declaration not allowed in struct/union scope
decl1.c(109) : error: 'm1': Invalid storage class in struct/union scope
decl1.c(110) : error: 'm2': Invalid storage class in struct/union scope
decl1.c(111) : error: 'm3': Invalid storage class in struct/union scope
decl1.c(112) : error: 'm4': Invalid storage class in struct/union scope
decl1.c(113) : error: 'm5': Invalid storage class in struct/union scope
decl1.c(116) : error: 'm6': already declared in this scope
     decl1.c(115) : See previous declaration of 'm6'
decl1.c(132) : error: 'g13': already declared in this scope
     decl1.c(131) : See previous declaration of 'g13'
decl1.c(142) : error: 'g16' already declared with a different storage class
     decl1.c(137) : See previous declaration of 'g16'
