Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 12.00.8804 for 80x86
Copyright (C) Microsoft Corp 1984-1998. All rights reserved.

scan1.c
scan1.c(1) : warning: Ignoring #pragma
scan1.c(1) : warning: Ignoring #pragma
scan1.c(3) : error: '(' expected after _Pragma
scan1.c(4) : error: A string expected after _Pragma(
scan1.c(5) : error: ')' expected after _Pragma(string
scan1.c(5) : warning: Ignoring #pragma
scan1.c(5) : warning: Empty statement at file scope
scan1.c(10) : error: Bad octal number
scan1.c(11) : error: Invalid hex number
scan1.c(13) : error: Number expected after exponent
scan1.c(15) : error: Bad floating point constant
scan1.c(16) : error: Bad floating point constant
scan1.c(17) : error: Bad floating point constant
scan1.c(20) : error: '..' is invalid. Did you mean '...'?
scan1.c(22) : error: Bad character '\x40'
scan1.c(26) : error: Unterminated character constant
scan1.c(29) : error: Bad escape character
scan1.c(30) : error: Ill-formed universal character
scan1.c(33) : error: Unterminated character constant
scan1.c(33) : error: at '' : parse error, unexpected $, expecting ';'
