Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 12.00.8804 for 80x86
Copyright (C) Microsoft Corp 1984-1998. All rights reserved.

xattr1.c
xattr1.c(1) : error: '__attr(wrong)': unrecognized __attr
xattr1.c(3) : error: 'func2': type is incompatible with previous declaration
     xattr1.c(2) : See previous declaration of 'func2'
xattr1.c(4) : error: More than one calling convention attribute
xattr1.c(5) : error: More than one calling convention attribute
xattr1.c(8) : error: More than one pointer size attribute
xattr1.c(9) : error: More than one pointer size attribute
xattr1.c(11) : error: 'v4': type is incompatible with previous declaration
     xattr1.c(10) : See previous declaration of 'v4'
