	TITLE	test.c
	.386P
include listing.inc
if @Version gt 510
.model FLAT
else
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
_BSS	SEGMENT DWORD USE32 PUBLIC 'BSS'
_BSS	ENDS
_TLS	SEGMENT DWORD USE32 PUBLIC 'TLS'
_TLS	ENDS
;	COMDAT _test
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
FLAT	GROUP _DATA, CONST, _BSS
	ASSUME	CS: FLAT, DS: FLAT, SS: FLAT
endif
_DATA	SEGMENT
COMM	_p:DWORD
COMM	_res:BYTE
_DATA	ENDS
PUBLIC	_test
;	COMDAT _test
_TEXT	SEGMENT
_test	PROC NEAR					; COMDAT

; 6    :   res = *(char *)&p;

	mov	al, BYTE PTR _p
	mov	BYTE PTR _res, al

; 7    : }

	ret	0
_test	ENDP
_TEXT	ENDS
END
