#line 2 "scan.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 110
#define YY_END_OF_BUFFER 111
static yyconst short int yy_accept[306] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  111,   80,    3,    4,   80,   65,   80,   80,
       67,   80,   80,   80,   80,   80,   70,   74,   56,   80,
       58,   80,   69,   69,   80,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   80,    3,    5,  107,  106,  107,  109,  108,   91,
       88,   81,   91,   91,  102,   99,   92,  102,  102,  104,
      103,    3,   55,   44,   53,   47,   42,   62,   45,   63,
       46,   64,   41,   75,    1,    2,   43,   75,   70,   71,
       77,   70,   70,   73,   74,   74,   74,   60,   57,   54,

       59,   61,   79,   69,   66,   68,   49,   69,   69,   69,
       69,   69,   69,   69,   14,   69,   69,   69,   69,   69,
       69,   18,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   48,   52,    3,    5,  105,   90,   87,
       86,   82,   84,   83,   85,  101,   98,   97,   93,   95,
       94,   96,   40,   75,   70,   70,   71,   71,   77,   76,
       70,   70,   72,   73,   73,   74,   74,   50,   51,   78,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   19,   69,   26,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,

       69,   89,   84,   85,  100,   95,   96,   70,   70,   71,
       71,   76,   72,   72,   73,   73,   69,   69,   34,   69,
        9,   27,   69,   69,   69,   69,   12,   15,   69,   69,
       16,   28,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   25,   69,   69,   84,   85,   95,   96,
       72,   72,   69,   69,   17,   31,   69,   69,   69,   69,
       30,   69,   69,   22,   69,   69,   69,   69,   69,   69,
       20,   69,   69,   13,   39,   69,   69,   69,   24,   33,
       69,   21,   23,   10,   35,    7,    6,   69,   69,   69,
       69,   69,   11,   69,   37,   69,   69,   69,    8,   36,

       29,   32,   69,   38,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       10,   11,   12,    1,   13,   14,   15,   16,   17,   17,
       17,   17,   17,   17,   17,   18,   18,    1,    1,   19,
       20,   21,   22,    1,   23,   23,   23,   23,   24,   25,
       26,   26,   26,   26,   26,   27,   26,   26,   26,   26,
       26,   26,   26,   26,   28,   26,   26,   29,   26,   26,
        1,   30,    1,   31,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   26,   42,   43,   44,   45,
       46,   47,   26,   48,   49,   50,   51,   52,   53,   54,
       55,   56,    1,   57,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[58] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    2,    2,    1,    1,
        1,    1,    2,    2,    2,    3,    4,    4,    3,    1,
        1,    3,    2,    2,    2,    2,    2,    2,    3,    3,
        3,    3,    4,    3,    3,    3,    3,    3,    3,    3,
        4,    3,    3,    3,    3,    3,    1
    } ;

static yyconst short int yy_base[319] =
    {   0,
        0,   56,   56,   57,  463,  462,   58,   61,   62,   67,
      461,  460,  462,  467,  459,  467,  440,  467,  439,   61,
      467,  438,   62,   65,   82,   90,   97,  138,   53,  437,
       73,  434,    0,   70,  435,  422,  402,  404,   62,   66,
       64,   44,  405,   78,  404,  412,   79,  393,  402,  400,
      405,   84,  125,  467,  467,  467,  429,  467,  467,  467,
      467,  467,  421,  187,  467,  467,  467,  420,  239,  467,
      467,  439,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  426,  278,  467,  467,  467,    0,  308,  346,
      126,   94,   90,  131,    0,  102,  120,  419,  467,  467,

      467,  418,  203,    0,  467,  467,  467,  113,  387,  399,
      386,  401,  388,  394,  379,  347,  344,  344,  347,  344,
      341,    0,  340,  343,  111,  341,  121,  124,  345,  338,
       87,   94,  343,  467,  467,  162,  467,  467,  255,  467,
      467,  467,  153,  467,    0,  329,  467,  467,  467,  162,
      467,    0,  467,  467,  148,  140,  157,  157,  170,  211,
      467,  467,  183,  163,  188,  467,  467,  467,  467,  467,
      332,  344,  334,  346,  341,  329,  144,  343,  341,  335,
      327,  332,  335,    0,  321,    0,  327,  324,  310,  310,
      312,  319,  305,  303,  303,  315,  301,  305,  307,  308,

      297,  467,  229,    0,  467,  234,    0,  467,  467,  467,
      467,  467,  202,  235,  467,  467,  287,  299,    0,  289,
        0,    0,  280,  288,  277,  284,    0,    0,  275,  270,
        0,    0,  270,  270,  267,  277,  267,  271,  276,  275,
      273,  263,  268,    0,  256,  267,  467,  467,  467,  467,
      467,  467,  253,  257,    0,    0,  254,  255,  260,  247,
        0,  240,  243,    0,  250,  247,  248,  232,  241,  243,
        0,  234,  230,    0,    0,  218,  215,  213,    0,    0,
      223,    0,    0,    0,    0,    0,    0,  220,  206,  197,
      186,  182,    0,  158,    0,  166,  164,  161,    0,    0,

        0,    0,  162,    0,  467,  397,  401,  405,  409,  413,
      416,  420,  424,  427,  193,  171,  104,   75
    } ;

static yyconst short int yy_def[319] =
    {   0,
      305,    1,  306,  306,  307,  307,  308,  308,  309,  309,
      310,  310,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  311,  311,  305,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  312,  305,  305,  305,  305,  313,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,   84,  305,  305,
      305,  305,  305,  314,   28,  305,  305,  305,  305,  305,

      305,  305,  305,  311,  305,  305,  305,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  315,  305,  305,  305,  305,  305,
      305,  316,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  314,  305,  305,  305,  305,  305,  305,  305,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,

      311,  305,  305,  317,  305,  305,  318,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  305,  305,  305,  305,
      305,  305,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,

      311,  311,  311,  311,    0,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305
    } ;

static yyconst short int yy_nxt[525] =
    {   0,
       14,   15,   16,   17,   18,   14,   19,   20,   21,   14,
       22,   23,   24,   25,   26,   27,   28,   28,   29,   30,
       31,   32,   33,   33,   33,   33,   34,   33,   33,   14,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   33,
       44,   33,   45,   33,   33,   33,   33,   46,   47,   48,
       49,   50,   51,   33,   33,   33,   52,   53,   56,   56,
       61,   54,   62,   61,   66,   62,   57,   57,   75,   66,
       67,   98,   99,   78,  105,   67,  250,   80,  106,   63,
       76,   79,   63,   68,   81,   82,  119,   64,   68,  120,
       64,   69,  101,  102,  111,   83,   69,   84,   84,   84,

       85,  112,  114,  134,   86,  248,  116,  113,  117,   87,
       88,  115,   89,   89,   90,  122,  162,  118,  126,  127,
       91,  161,  123,   92,   93,   94,  136,  197,  128,  166,
      137,  129,  162,   91,  199,  198,  200,  159,  159,   92,
      135,  160,  160,  160,  161,  171,  167,   93,  172,  188,
       94,   88,  166,   95,   95,   95,  193,  164,  165,  191,
      189,   91,  167,  136,   96,   97,  209,  137,  203,  203,
      203,  194,  207,  164,   91,  208,  192,  206,  206,  206,
       96,  165,  209,  211,  210,  160,  160,  160,   97,  141,
      215,  142,  223,  224,  204,  142,  304,  303,  208,  211,

      302,  301,  143,  143,  143,  300,  170,  210,  142,  213,
      214,  170,  170,  215,  216,  170,  142,  170,  299,  144,
      144,  170,  170,  170,  144,  213,  160,  160,  160,  251,
      216,  144,  298,  214,  144,  212,  144,  212,  144,  297,
      145,  148,  296,  149,  247,  247,  247,  149,  212,  249,
      249,  249,  251,  212,  150,  150,  150,  295,  202,  294,
      149,  252,  293,  202,  202,  292,  291,  202,  149,  202,
      290,  151,  151,  202,  202,  202,  151,  252,  289,  288,
      287,  286,  285,  151,  284,  283,  151,  282,  151,  281,
      151,  280,  152,   84,   84,   84,  279,  278,  277,  276,

      275,   91,  154,  274,  154,  273,  272,  271,  270,  269,
      268,  267,  266,  265,   91,  154,  264,  263,  262,  261,
      154,   88,  260,   89,   89,   90,  259,  258,  257,  256,
      255,   91,  205,  254,  155,  156,  253,  205,  205,  246,
      245,  205,  244,  205,   91,  243,  242,  205,  205,  205,
      155,  241,  240,  239,  238,  237,  236,  235,  156,   88,
      234,   90,   90,   90,  233,  232,  231,  230,  229,   91,
      228,  227,  157,  158,  226,  225,  222,  221,  220,  219,
      218,  217,   91,  201,  196,  195,  190,  187,  157,  186,
      185,  184,  183,  182,  181,  180,  158,   55,   55,   55,

       55,   58,   58,   58,   58,   60,   60,   60,   60,   65,
       65,   65,   65,   70,   70,   70,   70,  104,  104,  104,
      140,  140,  140,  140,  147,  147,  147,  147,  163,  179,
      163,  178,  177,  176,  175,  174,  173,  169,  168,  153,
       72,  146,  139,  138,  133,  132,  131,  130,  125,  124,
      121,  110,  109,  108,  107,  103,  100,   77,   74,   73,
       72,  305,   71,   71,   59,   59,   13,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,

      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305
    } ;

static yyconst short int yy_chk[525] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,    3,    4,
        7,    2,    7,    8,    9,    8,    3,    4,   20,   10,
        9,   29,   29,   23,   34,   10,  318,   24,   34,    7,
       20,   23,    8,    9,   24,   24,   42,    7,   10,   42,
        8,    9,   31,   31,   39,   25,   10,   25,   25,   25,

       26,   39,   40,   52,   26,  317,   41,   39,   41,   26,
       27,   40,   27,   27,   27,   44,   93,   41,   47,   47,
       27,   92,   44,   27,   27,   27,   53,  131,   47,   96,
       53,   47,   93,   27,  132,  131,  132,   91,   91,   27,
       52,   91,   91,   91,   92,  108,   97,   27,  108,  125,
       27,   28,   96,   28,   28,   28,  128,   94,   94,  127,
      125,   28,   97,  136,   28,   28,  156,  136,  143,  143,
      143,  128,  316,   94,   28,  155,  127,  150,  150,  150,
       28,   94,  156,  158,  157,  159,  159,  159,   28,   64,
      164,   64,  177,  177,  315,   64,  303,  298,  155,  158,

      297,  296,   64,   64,   64,  294,  103,  157,   64,  163,
      163,  103,  103,  164,  165,  103,   64,  103,  292,   64,
       64,  103,  103,  103,   64,  163,  160,  160,  160,  213,
      165,   64,  291,  163,   64,  160,   64,  160,   64,  290,
       64,   69,  289,   69,  203,  203,  203,   69,  160,  206,
      206,  206,  213,  160,   69,   69,   69,  288,  139,  281,
       69,  214,  278,  139,  139,  277,  276,  139,   69,  139,
      273,   69,   69,  139,  139,  139,   69,  214,  272,  270,
      269,  268,  267,   69,  266,  265,   69,  263,   69,  262,
       69,  260,   69,   84,   84,   84,  259,  258,  257,  254,

      253,   84,   84,  246,   84,  245,  243,  242,  241,  240,
      239,  238,  237,  236,   84,   84,  235,  234,  233,  230,
       84,   89,  229,   89,   89,   89,  226,  225,  224,  223,
      220,   89,  146,  218,   89,   89,  217,  146,  146,  201,
      200,  146,  199,  146,   89,  198,  197,  146,  146,  146,
       89,  196,  195,  194,  193,  192,  191,  190,   89,   90,
      189,   90,   90,   90,  188,  187,  185,  183,  182,   90,
      181,  180,   90,   90,  179,  178,  176,  175,  174,  173,
      172,  171,   90,  133,  130,  129,  126,  124,   90,  123,
      121,  120,  119,  118,  117,  116,   90,  306,  306,  306,

      306,  307,  307,  307,  307,  308,  308,  308,  308,  309,
      309,  309,  309,  310,  310,  310,  310,  311,  311,  311,
      312,  312,  312,  312,  313,  313,  313,  313,  314,  115,
      314,  114,  113,  112,  111,  110,  109,  102,   98,   83,
       72,   68,   63,   57,   51,   50,   49,   48,   46,   45,
       43,   38,   37,   36,   35,   32,   30,   22,   19,   17,
       15,   13,   12,   11,    6,    5,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,

      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "scan.l"
#define INITIAL 0
#line 2 "scan.l"
#include <io.h>

#include <stdarg.h>

#include "port\global.h"
#include "comp.h"
#include "c_tab.h"

// Global variables accessible from external modules
//
int yycurline = 1;
unsigned yyidhash; // hash value of current ident

// Define several tables for minor issues like trigraphs and
//
#include "lextabs.inc"

#define GET_TRIGRAPH(c) TrigraphTable[(c) - FIRST_TRIGRAPH]
#define GET_ESCAPE(c)   EscapeTable[(c) - FIRST_ESCAPE]

#define RET_E( e_code, lex_code )  yylval.ecode = (e_code); return lex_code

#define RET_ITOK( i_tok, lex_code ) yylval.itok = (i_tok); return lex_code

/* C identifier */
/* C whitespace */
/* integer suffix */
/* floating point suffix */
/* a fractional number */
/* a fractional or integer number */
/* exponent */ 
/* a trigraph */
/* a character escape */
#define COMMENT 1
#define LINE_COMMENT 2
#define STR_STATE 3
#define CHAR_STATE 4
#define PREPR_DIR 5

#line 625 "scan.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 66 "scan.l"


#line 778 "scan.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 306 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 467 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 68 "scan.l"
BEGIN( COMMENT );
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 69 "scan.l"
BEGIN( LINE_COMMENT );
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 70 "scan.l"
/* eat up whitespace */
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 72 "scan.l"
++yycurline;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 74 "scan.l"
BEGIN(PREPR_DIR);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 76 "scan.l"
return SWITCH;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 77 "scan.l"
return STRUCT;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 78 "scan.l"
return CONTINUE;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 79 "scan.l"
return CASE;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 80 "scan.l"
return SIZEOF;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 81 "scan.l"
return DEFAULT;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 82 "scan.l"
return ELSE;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 83 "scan.l"
return WHILE;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 84 "scan.l"
return DO;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 85 "scan.l"
return ENUM;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 86 "scan.l"
return GOTO;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 87 "scan.l"
return BREAK;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 88 "scan.l"
return IF;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 89 "scan.l"
return FOR;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 90 "scan.l"
return UNION;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 91 "scan.l"
return RETURN;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 93 "scan.l"
RET_ITOK( TOK_SHORT, TYPESPEC );
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 94 "scan.l"
RET_ITOK( TOK_SIGNED, TYPESPEC );
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 95 "scan.l"
RET_ITOK( TOK_DOUBLE, TYPESPEC );
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 96 "scan.l"
RET_ITOK( TOK_VOID, TYPESPEC );
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 97 "scan.l"
RET_ITOK( TOK_INT, TYPESPEC );
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 98 "scan.l"
RET_ITOK( TOK_CHAR, TYPESPEC );
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 99 "scan.l"
RET_ITOK( TOK_LONG, TYPESPEC );
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 100 "scan.l"
RET_ITOK( TOK_UNSIGNED, TYPESPEC );
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 101 "scan.l"
RET_ITOK( TOK_FLOAT, TYPESPEC );
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 103 "scan.l"
RET_ITOK( TOK_CONST, TYPEQUAL );
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 104 "scan.l"
RET_ITOK( TOK_VOLATILE, TYPEQUAL );
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 106 "scan.l"
RET_ITOK( TOK_EXTERN, SCLASS );
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 107 "scan.l"
RET_ITOK( TOK_AUTO, SCLASS );
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 108 "scan.l"
RET_ITOK( TOK_STATIC, SCLASS );
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 109 "scan.l"
RET_ITOK( TOK_REGISTER, SCLASS );
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 110 "scan.l"
RET_ITOK( TOK_TYPEDEF, SCLASS );
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 112 "scan.l"
return DECLSPEC;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 113 "scan.l"
return ATTR;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 115 "scan.l"
return ELLIPSIS; 
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 116 "scan.l"
LexerError(".. is invalid"); return '.';
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 118 "scan.l"
RET_E( e_asgn_mul, ASSIGN );
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 119 "scan.l"
RET_E( e_asgn_div, ASSIGN );
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 120 "scan.l"
RET_E( e_asgn_mod, ASSIGN );
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 121 "scan.l"
RET_E( e_asgn_plus, ASSIGN );
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 122 "scan.l"
RET_E( e_asgn_minus, ASSIGN );
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 123 "scan.l"
RET_E( e_asgn_and, ASSIGN );
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 124 "scan.l"
RET_E( e_asgn_or, ASSIGN );
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 125 "scan.l"
RET_E( e_asgn_xor, ASSIGN );
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 126 "scan.l"
RET_E( e_asgn_shl, ASSIGN );
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 127 "scan.l"
RET_E( e_asgn_shr, ASSIGN );
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 129 "scan.l"
RET_E( e_log_or, LOG_OR );
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 130 "scan.l"
RET_E( e_log_and, LOG_AND );
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 132 "scan.l"
RET_E( e_eq, EQCOMPARE );
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 133 "scan.l"
RET_E( e_ne, EQCOMPARE );
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 135 "scan.l"
RET_E( e_less, ARITHCOMPARE );
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 136 "scan.l"
RET_E( e_le_eq, ARITHCOMPARE );
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 137 "scan.l"
RET_E( e_greater, ARITHCOMPARE );
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 138 "scan.l"
RET_E( e_gr_eq, ARITHCOMPARE );
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 140 "scan.l"
RET_E( e_shl, SHIFT );
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 141 "scan.l"
RET_E( e_shr, SHIFT );
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 143 "scan.l"
return INC;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 144 "scan.l"
return DEC;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 146 "scan.l"
RET_E( e_struct_deref, PTR );
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 148 "scan.l"
BEGIN( STR_STATE );
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 149 "scan.l"
BEGIN( STR_STATE );
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 150 "scan.l"
BEGIN( CHAR_STATE );
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 151 "scan.l"
BEGIN( CHAR_STATE );
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 153 "scan.l"
{
                  return
                    (yylval.sym = FindLocalSymbol(
                                      yytext,
                                      yyidhash=CalcStringHash( yytext ) )
                                    ) != NULL
                    &&
                    yylval.sym->storage->storClass == SC_TYPEDEF
                    ? TYPENAME : IDENT;
                }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 164 "scan.l"
return NUMBER; // octal number. 
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 165 "scan.l"
LexerError( "Invalid octal number" );
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 167 "scan.l"
return NUMBER; // hex number.
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 168 "scan.l"
LexerError( "Invalid hex number" );
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 170 "scan.l"
return NUMBER; // dec number
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 172 "scan.l"
return F_NUMBER; // floating point without exponent
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 173 "scan.l"
return F_NUMBER; // floating point with exponent
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 175 "scan.l"
LexerError( "Number expected after exponent" );
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 177 "scan.l"
return GET_TRIGRAPH( yytext[2] );
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 178 "scan.l"
LexerError( "Invalid trigraph" );
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 180 "scan.l"
return *yytext;
	YY_BREAK

case 81:
YY_RULE_SETUP
#line 183 "scan.l"
BEGIN(INITIAL); return STRING;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 185 "scan.l"
yytext[1];
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 186 "scan.l"
GET_ESCAPE(yytext[1]);
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 188 "scan.l"

	YY_BREAK
case 85:
YY_RULE_SETUP
#line 190 "scan.l"

	YY_BREAK
case 86:
YY_RULE_SETUP
#line 192 "scan.l"
++yycurline;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 193 "scan.l"
LexerError("Unrecognized character escape '%c'", yytext[1] );
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 195 "scan.l"
LexerError("Unterminated string constant"); ++yycurline; BEGIN(INITIAL);
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 197 "scan.l"
GET_TRIGRAPH( yytext[2] );
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 198 "scan.l"
// add to string
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 199 "scan.l"

	YY_BREAK


case 92:
YY_RULE_SETUP
#line 203 "scan.l"
BEGIN(INITIAL); return NUMBER;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 205 "scan.l"
yytext[1];
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 206 "scan.l"
GET_ESCAPE(yytext[1]);
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 208 "scan.l"

	YY_BREAK
case 96:
YY_RULE_SETUP
#line 210 "scan.l"

	YY_BREAK
case 97:
YY_RULE_SETUP
#line 212 "scan.l"
++yycurline;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 213 "scan.l"
LexerError("Unrecognized character escape '%c'", yytext[1] );
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 215 "scan.l"
LexerError("Unterminated character constant"); ++yycurline; BEGIN(INITIAL);
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 217 "scan.l"
GET_TRIGRAPH( yytext[2] );
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 218 "scan.l"
// add to string
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 219 "scan.l"

	YY_BREAK


case 103:
YY_RULE_SETUP
#line 223 "scan.l"
++yycurline; BEGIN(INITIAL);
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 224 "scan.l"

	YY_BREAK


case 105:
YY_RULE_SETUP
#line 228 "scan.l"
BEGIN(INITIAL);
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 229 "scan.l"
++yycurline;
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 230 "scan.l"

	YY_BREAK


case 108:
YY_RULE_SETUP
#line 234 "scan.l"
++yycurline; BEGIN(INITIAL); 
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 235 "scan.l"

	YY_BREAK

case 110:
YY_RULE_SETUP
#line 238 "scan.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1431 "scan.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(LINE_COMMENT):
case YY_STATE_EOF(STR_STATE):
case YY_STATE_EOF(CHAR_STATE):
case YY_STATE_EOF(PREPR_DIR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 306 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 306 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 305);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 238 "scan.l"


#ifdef TEST_YYLEX

void LexerError ( const char * str, ... )
{
  va_list ap;
  va_start( ap, str );

  fprintf( stderr, "line %d:", yycurline );
  vfprintf( stderr, str, ap );
  printf( "\n" );

  va_end( ap );
};

int main ( void )
{
  int c;
  while (c = yylex())
  {
    printf( "%d\n", c );
  }
  return 0;
};
#endif
