#line 2 "scan.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 154
#define YY_END_OF_BUFFER 155
static yyconst short int yy_accept[319] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      155,   77,    3,    4,   41,   24,   43,   36,   22,   28,
       29,   37,   38,   72,   39,   32,   42,   10,   12,   57,
       58,   46,   61,   47,   56,    9,    9,   26,    6,   27,
       52,    9,   30,   53,   31,   40,    3,    5,  150,  149,
      150,  153,  152,  153,  147,  145,  147,   95,   94,   78,
       96,  114,  113,   97,  115,  118,  119,  117,  117,  124,
      125,  123,  122,  141,  140,  126,  142,  144,  143,  144,
        3,   51,   64,   76,   54,   67,   62,   34,   65,   35,

       66,   33,   60,   15,    1,    2,   63,   15,   10,   11,
       17,   10,   10,   14,   10,   12,   12,   12,   12,   74,
       75,   73,   44,   48,   50,   49,   45,    9,    8,   25,
       23,   69,    9,   68,   55,    3,    5,  150,  148,  153,
      151,  147,  146,   95,   93,   92,   79,   88,   91,   80,
       81,   87,   82,   83,   84,   85,   91,   86,   93,  114,
      112,  111,   98,  107,  110,   99,  100,  106,  101,  102,
      103,  104,  110,  105,  112,  117,  117,  123,  121,  121,
      141,  139,  138,  127,  136,  128,  129,  135,  130,  131,
      132,  133,  134,  139,  143,   59,   15,   10,   10,   10,

       11,   11,   11,   17,   16,   10,   10,   10,   10,   21,
       21,   13,   14,   14,   14,   12,   12,   12,   12,   70,
       71,    9,   88,   91,   91,   89,  107,  110,  110,  108,
      117,  117,  121,  121,  136,  137,   10,   10,   10,   10,
       11,   11,   11,   11,   16,   10,   10,   20,   20,   13,
       13,   19,   13,   13,   14,   14,   14,   14,   12,   12,
        9,   88,   91,   91,  107,  110,  110,  117,  117,  121,
      121,  136,   10,   10,   11,   11,   13,   13,   19,   18,
       13,   13,   14,   14,    9,   91,   91,  110,  110,  117,
      116,  121,  121,   13,   18,   13,    9,   91,   90,  110,

      109,  117,  121,  120,    7,   91,  110,  117,  121,    7,
       91,  110,  117,  121,   91,  110,  121,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   27,   27,   27,   28,   29,
       30,   30,   30,   30,   30,   31,   30,   30,   30,   32,
       30,   30,   30,   30,   33,   30,   30,   34,   30,   30,
       35,   36,   37,   38,   39,    1,   40,   41,   27,   27,

       42,   43,   44,   30,   30,   30,   30,   45,   46,   47,
       30,   48,   30,   49,   30,   50,   51,   52,   30,   53,
       30,   30,   54,   55,   56,   57,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[58] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    5,    5,
        1,    1,    1,    1,    1,    1,    5,    5,    5,    6,
        6,    6,    6,    6,    1,    7,    1,    1,    6,    5,
        5,    5,    5,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[387] =
    {   0,
        0,   56,   56,   57,   58,   60,   61,   62,   63,   64,
       71,   72,   68,   76,  127,    0,   75,   78,   80,   82,
      478,  725,  475,  725,  452,  725,   61,   79,  725,  725,
      725,  451,   82,  725,   97,   97,  173,  182,  220,  449,
      725,   81,  449,   65,  725,  436,  182,  725,  725,  725,
      447,   88,  725,   68,  725,  725,  186,  725,    0,  725,
      452,    0,  725,  464,    0,  725,  463,    0,  725,  725,
      269,    0,  725,  725,  320,  725,  725,    0,    0,  725,
      725,    0,  153,    0,  725,  725,  371,  725,  462,  725,
      461,  725,  725,  725,  725,  725,  725,  725,  725,  725,

      725,  725,  446,  407,  725,  725,  725,    0,  437,  473,
      210,  163,  158,  509,  160,    0,  175,  164,  186,  725,
      725,  725,  437,  725,  725,  725,  436,  423,  725,  725,
      725,  725,  163,  725,  725,  215,  725,    0,    0,    0,
      725,    0,  725,    0,  725,  725,  725,  107,    0,  725,
      725,  725,  725,  725,  725,  725,    0,  725,    0,    0,
      725,  725,  725,  223,    0,  725,  725,  725,  725,  725,
      725,  725,    0,  725,    0,    0,    0,    0,    0,    0,
        0,  725,  725,  725,  225,  725,  725,  725,  725,  725,
      725,  725,  725,    0,  456,  725,  725,  201,  214,  213,

      216,  223,  224,  261,  272,  222,  725,  423,  406,  725,
        0,  545,  253,  225,  249,  256,  725,  417,  402,  725,
      725,  257,  242,    0,    0,    0,  258,    0,    0,    0,
        0,    0,    0,    0,  280,    0,  263,  725,  415,  400,
      273,  725,  413,  398,  725,  725,  725,  218,  294,    0,
      297,  332,  282,  298,  303,  725,  411,  396,  725,  725,
       74,  725,    0,    0,  725,    0,    0,    0,    0,    0,
        0,  725,  725,  725,  725,  725,  304,  725,  314,  363,
      409,  394,  725,  725,  322,    0,    0,    0,    0,    0,
      725,    0,    0,  725,  725,  725,  304,    0,  725,    0,

      725,    0,    0,  725,  339,    0,    0,    0,    0,  435,
        0,    0,    0,    0,    0,    0,    0,  725,  596,  603,
      610,  617,  624,  631,  638,  645,  648,  655,  662,  669,
      676,  682,  689,  695,  429,  428,  698,  704,  710,  717,
      427,  426,  425,  424,  423,  417,  414,  412,  411,  410,
      405,  404,  400,  399,  398,  397,  396,  395,  394,  393,
      391,  390,  388,  386,  383,  382,  381,  380,  379,  374,
      373,  372,  361,  360,  359,  354,  352,  330,  303,  280,
      278,  258,  217,  215,  202,   65
    } ;

static yyconst short int yy_def[387] =
    {   0,
      318,    1,  319,  319,  320,  320,  321,  321,  322,  322,
      323,  323,  324,  324,  318,   15,  325,  325,  326,  326,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  327,  327,  318,  318,  318,
      318,  327,  318,  318,  318,  318,  318,  318,  328,  318,
      328,  329,  318,  329,  330,  318,  330,  331,  318,  318,
      332,  333,  318,  318,  334,  318,  318,  335,  336,  318,
      318,  337,  318,  338,  318,  318,  339,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,

      318,  318,  318,  318,  318,  318,  318,  104,  318,  318,
      318,  318,  318,  340,  318,   39,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  327,  318,  318,
      318,  318,  327,  318,  318,  318,  318,  328,  328,  329,
      318,  330,  318,  331,  318,  318,  318,  318,  341,  318,
      318,  318,  318,  318,  318,  318,  342,  318,  343,  333,
      318,  318,  318,  318,  344,  318,  318,  318,  318,  318,
      318,  318,  345,  318,  346,  347,  348,  337,  349,  350,
      338,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  351,  318,  318,  318,  318,  318,  318,

      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      352,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  327,  318,  353,  354,  343,  318,  355,  356,  346,
      357,  358,  359,  360,  318,  351,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  352,  352,  212,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      327,  318,  361,  362,  318,  363,  364,  365,  366,  367,
      368,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  327,  369,  370,  371,  372,  373,
      318,  374,  375,  318,  318,  318,  327,  376,  318,  377,

      318,  378,  379,  318,  327,  380,  381,  382,  383,  318,
      384,  385,  366,  386,  370,  372,  375,    0,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318
    } ;

static yyconst short int yy_nxt[783] =
    {   0,
       22,   23,   24,   25,   26,   22,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   39,
       40,   41,   42,   43,   44,   45,   46,   46,   46,   46,
       47,   46,   46,   46,   48,   49,   50,   51,   52,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   53,   54,   55,   56,   57,   60,   60,
       63,   58,   63,   66,   66,   69,   69,   61,   61,  317,
       77,   70,   70,   73,   73,   74,   74,   85,   77,   86,
       85,   89,   86,   89,   93,   94,   95,  121,  126,  127,
       90,  134,   90,   64,   98,   64,   67,   67,   71,   71,

       78,  122,   96,  123,  124,   99,   75,   75,   78,  129,
       87,  100,  103,   87,  104,  104,  104,  285,   79,  133,
      101,  102,  135,  129,  223,  223,   79,   80,   80,   81,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   82,   82,   82,   80,   80,   80,
       80,   80,   80,   82,   82,   82,   82,   82,   82,   82,
       82,   80,   83,   80,   80,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       80,   80,   80,   80,  105,  179,  130,  136,  208,  106,
      131,  137,  207,  206,  218,  207,  107,  108,  129,  109,

      109,  110,  209,  180,  206,  216,  316,  217,  219,  111,
      207,  222,  112,  207,  113,  114,  136,  129,  217,  315,
      137,  314,  204,  111,  204,  217,  115,  205,  205,  205,
      216,  237,  113,  238,  114,  108,  217,  116,  116,  116,
      227,  227,  235,  235,  239,  238,  241,  111,  242,  252,
      117,  238,  118,  243,  246,  257,  242,  237,  240,  262,
      262,  111,  313,  238,  119,  252,  242,  244,  241,  258,
      118,  146,  246,  147,  242,  265,  265,  147,  205,  205,
      205,  256,  312,  255,  311,  256,  148,  148,  259,  205,
      205,  205,  129,  255,  147,  273,  261,  272,  272,  256,

      245,  149,  245,  256,  147,  275,  259,  309,  150,  151,
      152,  153,  281,  273,  245,  154,  245,  155,  156,  157,
      158,  159,  162,  275,  163,  252,  282,  277,  163,  278,
      278,  280,  280,  280,  308,  283,  294,  164,  164,  129,
      310,  252,  277,  305,  279,  163,  279,  278,  278,  280,
      280,  280,  165,  283,  294,  163,  307,  129,  306,  166,
      167,  168,  169,  304,  303,  302,  170,  297,  171,  172,
      173,  174,  175,  183,  129,  184,  301,  300,  299,  184,
      280,  280,  280,  298,  293,  292,  291,  290,  185,  185,
      289,  295,  288,  295,  287,  286,  184,  271,  270,  269,

      268,  267,  266,  264,  263,  295,  184,  295,  248,  236,
      186,  187,  188,  189,  234,  233,  232,  190,  231,  191,
      192,  230,  193,  194,  104,  104,  104,  229,  228,  226,
      225,  224,  177,  176,  111,  197,  310,  197,  296,  296,
      284,  284,  276,  276,  274,  274,  260,  260,  111,  197,
      247,  197,  108,  247,  109,  109,  110,  195,  129,  221,
      220,  196,   91,  195,  111,  143,  141,  198,  139,  199,
      132,  129,  125,  120,   97,   92,   91,  318,  111,  318,
      318,  200,  318,  318,  318,  318,  318,  199,  108,  318,
      110,  110,  110,  318,  318,  318,  318,  318,  318,  318,

      111,  318,  318,  201,  318,  202,  318,  318,  318,  318,
      318,  318,  318,  318,  111,  318,  318,  203,  318,  318,
      318,  318,  318,  202,  211,  318,  212,  212,  212,  318,
      318,  318,  318,  318,  318,  212,  212,  212,  318,  213,
      318,  214,  318,  318,  318,  318,  318,  318,  212,  212,
      212,  212,  318,  215,  318,  318,  318,  318,  318,  214,
      249,  318,  250,  250,  250,  318,  318,  318,  318,  318,
      318,  250,  250,  250,  318,  251,  252,  253,  318,  318,
      318,  318,  318,  318,  250,  250,  250,  250,  318,  254,
      318,  318,  252,  318,  318,  253,   59,   59,   59,   59,

       59,   59,   59,   62,   62,   62,   62,   62,   62,   62,
       65,   65,   65,   65,   65,   65,   65,   68,   68,   68,
       68,   68,   68,   68,   72,   72,   72,   72,   72,   72,
       72,   76,   76,   76,   76,   76,   76,   76,   84,   84,
       84,   84,   84,   84,   84,   88,   88,   88,   88,   88,
       88,   88,  128,  128,  128,  138,  318,  138,  138,  138,
      138,  138,  140,  318,  140,  140,  140,  140,  140,  142,
      318,  142,  142,  142,  142,  142,  144,  318,  144,  318,
      144,  144,  145,  145,  145,  145,  145,  145,  145,  160,
      318,  318,  160,  160,  160,  161,  161,  161,  161,  161,

      161,  161,  178,  178,  181,  318,  318,  181,  181,  181,
      182,  182,  182,  182,  182,  182,  182,  210,  318,  210,
      210,  210,  210,  210,   21,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318
    } ;

static yyconst short int yy_chk[783] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,    3,    4,
        5,    2,    6,    7,    8,    9,   10,    3,    4,  386,
       13,    9,   10,   11,   12,   11,   12,   17,   14,   17,
       18,   19,   18,   20,   27,   27,   28,   42,   44,   44,
       19,   54,   20,    5,   33,    6,    7,    8,    9,   10,

       13,   42,   28,   42,   42,   33,   11,   12,   14,  261,
       17,   35,   36,   18,   36,   36,   36,  261,   13,   52,
       35,   35,   54,   52,  148,  148,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   37,   83,   47,   57,  113,   37,
       47,   57,  115,  112,  118,  112,   37,   38,  133,   38,

       38,   38,  113,   83,  115,  117,  385,  117,  118,   38,
      115,  133,   38,  112,   38,   38,  136,   47,  119,  384,
      136,  383,  111,   38,  111,  117,   38,  111,  111,  111,
      119,  198,   38,  198,   38,   39,  119,   39,   39,   39,
      164,  164,  185,  185,  199,  200,  201,   39,  201,  248,
       39,  198,   39,  202,  206,  214,  203,  200,  199,  223,
      223,   39,  382,  200,   39,  248,  201,  202,  203,  214,
       39,   71,  206,   71,  203,  227,  227,   71,  204,  204,
      204,  215,  381,  213,  380,  213,   71,   71,  216,  205,
      205,  205,  222,  215,   71,  237,  222,  235,  235,  215,

      205,   71,  205,  213,   71,  241,  216,  379,   71,   71,
       71,   71,  253,  237,  205,   71,  205,   71,   71,   71,
       71,   71,   75,  241,   75,  249,  253,  251,   75,  251,
      254,  279,  279,  279,  378,  255,  277,   75,   75,  297,
      305,  249,  254,  297,  252,   75,  252,  251,  254,  252,
      252,  252,   75,  255,  277,   75,  377,  285,  376,   75,
       75,   75,   75,  375,  374,  373,   75,  285,   75,   75,
       75,   75,   75,   87,  305,   87,  372,  371,  370,   87,
      280,  280,  280,  369,  368,  367,  366,  365,   87,   87,
      364,  280,  363,  280,  362,  361,   87,  360,  359,  358,

      357,  356,  355,  354,  353,  280,   87,  280,  352,  351,
       87,   87,   87,   87,  350,  349,  348,   87,  347,   87,
       87,  346,   87,   87,  104,  104,  104,  345,  344,  343,
      342,  341,  336,  335,  104,  104,  310,  104,  282,  281,
      258,  257,  244,  243,  240,  239,  219,  218,  104,  104,
      209,  104,  109,  208,  109,  109,  109,  195,  128,  127,
      123,  103,   91,   89,  109,   67,   64,  109,   61,  109,
       51,   46,   43,   40,   32,   25,   23,   21,  109,    0,
        0,  109,    0,    0,    0,    0,    0,  109,  110,    0,
      110,  110,  110,    0,    0,    0,    0,    0,    0,    0,

      110,    0,    0,  110,    0,  110,    0,    0,    0,    0,
        0,    0,    0,    0,  110,    0,    0,  110,    0,    0,
        0,    0,    0,  110,  114,    0,  114,  114,  114,    0,
        0,    0,    0,    0,    0,  114,  114,  114,    0,  114,
        0,  114,    0,    0,    0,    0,    0,    0,  114,  114,
      114,  114,    0,  114,    0,    0,    0,    0,    0,  114,
      212,    0,  212,  212,  212,    0,    0,    0,    0,    0,
        0,  212,  212,  212,    0,  212,  212,  212,    0,    0,
        0,    0,    0,    0,  212,  212,  212,  212,    0,  212,
        0,    0,  212,    0,    0,  212,  319,  319,  319,  319,

      319,  319,  319,  320,  320,  320,  320,  320,  320,  320,
      321,  321,  321,  321,  321,  321,  321,  322,  322,  322,
      322,  322,  322,  322,  323,  323,  323,  323,  323,  323,
      323,  324,  324,  324,  324,  324,  324,  324,  325,  325,
      325,  325,  325,  325,  325,  326,  326,  326,  326,  326,
      326,  326,  327,  327,  327,  328,    0,  328,  328,  328,
      328,  328,  329,    0,  329,  329,  329,  329,  329,  330,
        0,  330,  330,  330,  330,  330,  331,    0,  331,    0,
      331,  331,  332,  332,  332,  332,  332,  332,  332,  333,
        0,    0,  333,  333,  333,  334,  334,  334,  334,  334,

      334,  334,  337,  337,  338,    0,    0,  338,  338,  338,
      339,  339,  339,  339,  339,  339,  339,  340,    0,  340,
      340,  340,  340,  340,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "scan.l"
#define INITIAL 0
#line 2 "scan.l"
#include "precomp.h"
#include "strings.h"
#include "cord.h"
#include "heap.h"
#include "tconf.h"
#include "options.h"
#include "scan.h"
#include "c.tab.h"
#include "comperr.h"

// This macro should have been defined. It stores the exact type of
// the operator (e_code) and returns a more general lexical cathegory
// token (lex_code)
//
#ifndef SCANNER_SET_E
  #define SCANNER_SET_E( e_code, lex_code )  (lex_code)
#endif

//=================================================================
// Global symbols that must be supplied in other modules
//

#ifndef ScannerError
  extern void ScannerError ( const char * str, ... );
#endif
#ifndef ScannerWarning
  extern void ScannerWarning ( const char * str, ... );
#endif
#ifndef ScannerPrepr
  extern void ScannerPrepr ( CORD );
#endif


//=================================================================
// Global variables accessible from external modules
//

int yycurline = 1;


//=================================================================
// Local data and definitions
//

#define SCANNER_SET_TC( tok ) (tok)
#define TC( tok, code )       (tok)

const static struct {
  const char * szText;
  int token;
} ReservedWords[] = 
{
//
// Standard words
//
  { "auto",            C_AUTO         },
  { "break",           BREAK          },
  { "case",            CASE           },
  { "continue",        CONTINUE       },
  { "default",         DEFAULT        },
  { "do",              DO             },
  { "else",            ELSE           },
  { "enum",            ENUM           },
  { "extern",          C_EXTERN       },
  { "for",             FOR            },
  { "goto",            GOTO           },
  { "if",              IF             },
  { "inline",          C_INLINE       },
  { "register",        C_REGISTER     },
  { "return",          RETURN         },
  { "sizeof",          SIZEOF         },
  { "static",          C_STATIC       },
  { "struct",          STRUCT         },
  { "switch",          SWITCH         },
  { "typedef",         C_TYPEDEF      },
  { "union",           UNION          },
  { "while",           WHILE          },

// QUAL
//
  { "const",           TC(QUAL, C_CONST    ) },
  { "restrict",        TC(QUAL, C_RESTRICT ) },
  { "volatile",        TC(QUAL, C_VOLATILE ) },

// TYPESPEC
//
  { "void",            TC(TYPESPEC, C_VOID      ) },
  { "char",            TC(TYPESPEC, C_CHAR      ) },
  { "short",           TC(TYPESPEC, C_SHORT     ) },
  { "int",             TC(TYPESPEC, C_INT       ) },
  { "long",            TC(TYPESPEC, C_LONG      ) },
  { "signed",          TC(TYPESPEC, C_SIGNED    ) },
  { "unsigned",        TC(TYPESPEC, C_UNSIGNED  ) },
  { "float",           TC(TYPESPEC, C_FLOAT     ) },
  { "double",          TC(TYPESPEC, C_DOUBLE    ) },
  { "_Bool",           TC(TYPESPEC, C__BOOL     ) },
  { "_Complex",        TC(TYPESPEC, C__COMPLEX  ) },
  { "_Imaginary",      TC(TYPESPEC, C__IMAGINARY) },

//
// Our extensions
//
  { "__declspec",      DECLSPEC       },
  { "__attr",          ATTR           },


//
// GNU C extensions
//
  { "__typeof__",      TYPEOF         },
  { "__alignof__",     ALIGNOF        },
  { "typeof",          TYPEOF         },
  { "__label__",       LABEL          },
  { "__inline__",      C_INLINE       },
  { "__attribute__",   GCC_ATTRIBUTE  },

//
// Just for testing
//
  { "typename",        TYPENAME },
};

#undef TC

#ifdef _DEBUG
static bool bWordsAdded = false;
#endif

static bool bWide; // whether we are currently processing a wide string/char

//--------------------------------------------------------------------------
// Name         InitReservedWords 
//
// 
//--------------------------------------------------------------------------
static void InitReservedWords ()
{
  int i;
  ASSERT( !bWordsAdded );

  for ( i = 0; i < _countof(ReservedWords); ++i )
  {
    STRING str;
    str = NewString( ReservedWords[i].szText );
    ASSERT( STRING_DATA(str)->token == 0 );
    STRING_DATA(str)->token = ReservedWords[i].token;
  }

#ifdef _DEBUG     
  bWordsAdded = true;
#endif
};

//--------------------------------------------------------------------------
// Name         StringFromCord 
//
// 
//--------------------------------------------------------------------------
static STRING StringFromCord ( CORD cord )
{
  STRING res;

  if (cord == NULL)
  {
    res = NULL;
  }
  else
  // A little optimization. If teh cord has only one segment
  // we can use it directly instead of allocating a buffer
  //
  if (cord->pNext == NULL)
  {
    res = NewStringLen( (char *)cord->u.data, cord->segLen );
  }
  else
  {
    char * pszBuffer, * dest;

    // Don't forget to reserve for the 0
    dest = pszBuffer = GC_ARRAY_NEW_ATOMIC( char, cord->totalLen + 1 );
    do
    {
      memcpy( dest, cord->u.data, cord->segLen );
      dest += cord->segLen;
      cord = cord->pNext;
    }
    while (cord != NULL);

    // no need to terminate the string fo NewStringLen

    res = NewStringLen( pszBuffer, dest - pszBuffer );

    // We don't really have to do this but just to signify that this buffer
    // is just temporary and will *never* be used again...
    GC_DELETE( pszBuffer ); 
  }

  return res;
};

//--------------------------------------------------------------------------
// Name         AppendChars 
//
// 
//--------------------------------------------------------------------------
static CORD AppendChars ( CORD cord, int leng, const char * text )
{
#if TARGET_CHAR_BIT == CHAR_BIT
  return Cord_NewSegment( cord, leng, text );
#else
  TCordSegment * pSeg = Cord_AllocSegment( sizeof(TARGET_CHAR) * leng );
  TARGET_CHAR * dest = (TARGET_CHAR *)pSeg->u.data;
  int i;

  for ( i = 0; i < leng; ++i )
  {
    if (bCharIsSigned)
    {
      change_integer_size( 
        sizeof(text[i]), &text[i],
        sizeof(dest[i]), &dest[i]
      );
    }
    else
    {
      change_unsigned_integer_size( 
        sizeof(text[i]), &text[i],
        sizeof(dest[i]), &dest[i]
      );
    }
  }

  return Cord_AddSegment( cord, pSeg );
#endif
};

//--------------------------------------------------------------------------
// Name         AppendWchars 
//
// 
//--------------------------------------------------------------------------
static CORD AppendWchars ( CORD cord, int leng, const char * text )
{
  TCordSegment * pSeg = Cord_AllocSegment( sizeof(TARGET_WCHAR) * leng );
  TARGET_WCHAR * dest = (TARGET_WCHAR *)pSeg->u.data;
  int i;

  for ( i = 0; i < leng; ++i )
  {
    if (bCharIsSigned)
    {
      change_integer_size( 
        sizeof(text[i]), &text[i],
        sizeof(dest[i]), &dest[i]
      );
    }
    else
    {
      change_unsigned_integer_size( 
        sizeof(text[i]), &text[i],
        sizeof(dest[i]), &dest[i]
      );
    }
  }

  return Cord_AddSegment( cord, pSeg );
};

//--------------------------------------------------------------------------
// Name         AppendText 
//
// This function convers from our native(host) character set in which
// the input program is written, to the destination character set
//--------------------------------------------------------------------------
static CORD AppendText ( CORD cord, int leng, const char * text )
{
  if (bWide)
    return AppendWchars( cord, leng, text );
  else
    return AppendChars( cord, leng, text );
};

//--------------------------------------------------------------------------
// Name         AppendWChar 
//
// Append a wchar_t to the string cord. 
// Converts teh wchar to char if necessary and checks for overflow 
// in which case issues an error.
//
// overflow_bit must already be set apropriately on entry to this function.
//--------------------------------------------------------------------------
static CORD AppendWChar ( CORD cord, TARGET_WCHAR * pwc )
{
  if (bWide)
  {
    if (!overflow_bit)
      overflow_bit = TARGET_GT_UNSIGNED( pwc, &TargetMaxWChar );

    if (overflow_bit)
      *pwc = TargetMaxWChar;

    cord = Cord_NewSegment( cord, sizeof(*pwc), pwc );
  }
  else
  {
    TARGET_CHAR c;

    if (!overflow_bit)
      TARGET_ASSIGN_UNSIGNED( &c, pwc ); 

    if (!overflow_bit)
      overflow_bit = TARGET_GT_UNSIGNED( &c, &TargetMaxUChar );

    if (overflow_bit)
      c = TargetMaxUChar;

    cord = Cord_NewSegment( cord, sizeof(c), &c );
  }

  if (overflow_bit)
    ScannerError( "Value too big for a character" );

  return cord;
};

//--------------------------------------------------------------------------
// Name         OctalEscape
//
// The parameter is in format \\[0-7]{1,3}
//--------------------------------------------------------------------------
static CORD OctalEscape ( CORD cord, const char * text )
{
  TARGET_WCHAR w;
  unsigned value = 0;

  while (*++text) // preincrement to skip over the '\\'
    value = (value << 3) + *text - '0';

  ASSERT( value < 8u*8u*8u );

  TARGET_ASSIGN_HOST_UINT( &w, value );

  return AppendWChar( cord, &w );
};

//--------------------------------------------------------------------------
// Name         ConvertHex 
//
// Convert a hex string into a wchar_t.
// Sets overflow_bit on overflow.
//--------------------------------------------------------------------------
static void ConvertHex ( const char * text, TARGET_WCHAR * pwc )
{
  TARGET_CLEAR_INT( pwc );

  do
  {
    TARGET_WCHAR tgtDigit;
    UCHAR digit = tolower(*text);

    if (digit >= 'a')
      digit -= 'a' - 10;
    else
      digit -= '0';

    TARGET_SHL_UNSIGNED( pwc, pwc, 4 );
    if (overflow_bit)
      break;

    TARGET_ASSIGN_8BIT( &tgtDigit, digit );
    TARGET_ADD_UNSIGNED( pwc, pwc, &tgtDigit );

    if (overflow_bit)
      break;
  }
  while (isxdigit( *++text ));
};

//--------------------------------------------------------------------------
// Name         HexEscape 
//
// The parameter is in format: \\x{XDIGIT}+
// It is not limited to any length, so it is possible it could overflow
// any integer type. So, we gather it in a TARGET_WCHAR which can hold all
// values of TARGET_CHAR. Then if we are not in wide mode we copy the WCHAR
// to the CHAR.
//--------------------------------------------------------------------------
static CORD HexEscape ( CORD cord, const char * text )
{
  TARGET_WCHAR wc;

  // skip the "\\x"
  ConvertHex( text + 2, &wc );
  return AppendWChar( cord, &wc );
};

//--------------------------------------------------------------------------
// Name         UniCharEscape 
//
// The parameter is in format: \\[uU]{XDIGIT}{1,8}
// It is not limited to any length, so it is possible it could overflow
// any integer type. So, we gather it in a TARGET_WCHAR which can hold all
// values of TARGET_CHAR. Then if we are not in wide mode we copy the WCHAR
// to the CHAR.
//--------------------------------------------------------------------------
static CORD UniCharEscape ( CORD cord, const char * text )
{
  TARGET_WCHAR wc;

  // skip the "\\[uU]"
  ConvertHex( text + 2, &wc );

  if (!overflow_bit)
  {
    // Must validate the character
/*
       [#2]   A  universal  character  name  shall  not  specify  a
       character short identifier in  the  range  00000000  through
       00000020,  0000007F  through  0000009F,  or 0000D800 through
       0000DFFF inclusive.  A universal character  name  shall  not
       designate a character in the required character set.
*/
    unsigned uc = UINT16_FROM_TARGET( &wc );

    if (overflow_bit || uc <= 0x009F || uc >= 0xD800 && uc <= 0xDFFF)
    {
      ScannerError( "Invalid universal character \\u%04x", uc );
      
      TARGET_ASSIGN_8BIT( &wc, ' ' );
      overflow_bit = 0;
    }
  }

  return AppendWChar( cord, &wc );
};

typedef struct TUniRange { unsigned l, h; } TUniRange;

//--------------------------------------------------------------------------
// Name         CmpUniRange 
//
// 
//--------------------------------------------------------------------------
static int CmpUniRange ( const void * _key, const void * _range )
{
  unsigned * key = (unsigned *)_key;
  TUniRange * range = (TUniRange *)_range;

  if (*key < range->l)
    return -1;
  if (*key <= range->h)
    return 0;
  return 1;
};

//--------------------------------------------------------------------------
// Name         ValidateIdentUniChar 
//
// The parameter is a [uU]{XDIGIT}{1,8}
// This function verifies whether the character can be used in an identifier
// and reports an error otherwise.
//--------------------------------------------------------------------------
void ValidateIdentUniChar ( const char * text )
{
  TARGET_WCHAR wc;

  // skip the "[uU]"
  ConvertHex( text + 1, &wc );

  if (!overflow_bit)
  {
    unsigned uc = UINT16_FROM_TARGET( &wc );
    if (!overflow_bit)
    {
      static const TUniRange ranges[] = 
      {
#include "srtuni\uni.inc"
      };

      if (bsearch( &uc, ranges, _countof(ranges), sizeof(ranges[0]), 
                   CmpUniRange ) != NULL)
      {
        return;
      }

      ScannerError( "Invalid universal character \\u%04x in identifier", uc );
      return;
    }
  }

  ScannerError( "Invalid universal character in identifier" );
};

//--------------------------------------------------------------------------
// Name         CharConst 
//
// 
//--------------------------------------------------------------------------
static int CharConst ( bool bReportEmpty, CORD cord )
{
  if (cord == NULL || cord->totalLen == 0)
  {
    if (bReportEmpty)
      ScannerError( "Empty character constant" );

    // Make a zero constant
    cord = AppendText( cord, 1, "" );
  }

  yylval.cord = cord;
  return bWide ? LCHAR_CONST : CHAR_CONST;
};

//--------------------------------------------------------------------------
// Name         StringConst 
//
// 
//--------------------------------------------------------------------------
static int StringConst ( CORD cord )
{
  if (cord == NULL)
    cord = AppendText( cord, 1, "" );

  yylval.cord = cord;
  return bWide ? LSTRING_CONST : STRING_CONST;
};

//--------------------------------------------------------------------------
// Name         Number 
//
//
// ISUFFIX  (([uU][lL]?)|([uU](ll|LL))|([lL][uU]?)|((ll|LL)[uU]?))
//--------------------------------------------------------------------------
static int Number ( int radix, const char * text )
{
  const char * tail;

  if (radix == 10)
  {
    tail = unsigned_integer_from_string( 
      sizeof(yylval.scanNum.value), 
      yytext, 
      &yylval.scanNum.value 
    );
  }
  else
  {
    TARGET_CLEAR_INT( &yylval.scanNum.value );

    // Calculate shift 
    radix = radix == 8 ? 3 : 4;

    for ( tail = yytext; isxdigit(*tail); ++tail )
    {
      TARGET_LARGEST_INT_TYPE tgtDigit;
      UCHAR digit = tolower(*tail);

      if (digit >= 'a')
        digit -= 'a' - 10;
      else
        digit -= '0';

      TARGET_SHL_UNSIGNED( &yylval.scanNum.value, &yylval.scanNum.value, radix );
      if (overflow_bit)
        break;

      TARGET_ASSIGN_8BIT( &tgtDigit, digit );
      TARGET_ADD_UNSIGNED( &yylval.scanNum.value, &yylval.scanNum.value, &tgtDigit );
      if (overflow_bit)
        break;
    }
  }

  if (!overflow_bit)
    overflow_bit = TARGET_GT_UNSIGNED( &yylval.scanNum.value, &TargetMaxLargest );

  if (overflow_bit)
    ScannerWarning( "Too long integer constant" );

  yylval.scanNum.bOctHex = radix != 10;
  yylval.scanNum.U = false;
  yylval.scanNum.L = 0;

/*
  [uU][lL]?
  [uU](ll|LL)
  [lL][uU]?
  (ll|LL)[uU]?
*/
  if (tail[0] == 'u' || tail[0] == 'U')
  {
    yylval.scanNum.U = true;
    if (tail[1] != 0)
    {
      if (tail[2] != 0)
        yylval.scanNum.L = 2;
      else
        yylval.scanNum.L = 1;
    }
  }
  else
  if (tail[0] != 0)
  {
    if (tail[1] != 'l' && tail[1] != 'L')
    {
      yylval.scanNum.L = 1;

      if (tail[1] != 0)
        yylval.scanNum.U = true;
    }
    else
    {
      yylval.scanNum.L = 2;

      if (tail[2] != 0)
        yylval.scanNum.U = true;
    }
  }

  return NUMBER;
};

/*
                    ||                       |
                    ||                       |  Octal or Hexadecimal
       Suffix       ||   Decimal Constant    |        Constant
       -------------++-----------------------+------------------------
       none         ||int                    | int
                    ||long int               | unsigned int
                    ||long long int          | long int
                    ||                       | unsigned long int
                    ||                       | long long int
                    ||                       | unsigned long long int
       -------------++-----------------------+------------------------
       u or U       ||unsigned int           | unsigned int
                    ||unsigned long int      | unsigned long int
                    ||unsigned long long int | unsigned long long int
       -------------++-----------------------+------------------------
       l or L       ||long int               | long int
                    ||long long int          | unsigned long int
                    ||                       | long long int
                    ||                       | unsigned long long int
       -------------++-----------------------+------------------------
       Both u or U  ||unsigned long int      | unsigned long int
       and l or L   ||unsigned long long int | unsigned long long int
       -------------++-----------------------+------------------------
       ll or LL     ||long long int          | long long int
                    ||                       | unsigned long long int
       -------------++-----------------------+------------------------
       Both u or U  ||unsigned long long int | unsigned long long int
       and ll or LL ||                       |

       If  an integer constant cannot be represented by any type in
       its list, it may have  an  extended  integer  type,  if  the
       extended  integer  type  can represent its value.  If all of
       the types in the list  for  the  constant  are  signed,  the
       extended  integer type shall be signed.  If all of the types
       in the list for the  constant  are  unsigned,  the  extended
       integer  type  shall be unsigned.  If the list contains both
       signed and unsigned types, the extended integer type may  be
       signed or unsigned.
*/


//--------------------------------------------------------------------------
// Name         F_Number 
//
// 
//--------------------------------------------------------------------------
static int F_Number ( int leng, const char * yytext )
{
  int oldRound = IEEE_set_round( IEEE_RN ); // round to nearest

  switch (yytext[leng-1])
  {
  case 'f': case 'F':
    IEEE_single_from_string( yytext, &yylval.scanFNum.value.flt );
    yylval.scanFNum.kind = 0;
    break;

  default:
    IEEE_double_from_string( yytext, &yylval.scanFNum.value.dbl );
    yylval.scanFNum.kind = 1;
    break;

  case 'l': case 'L':
    IEEE_double_from_string( yytext, &yylval.scanFNum.value.ldbl );
    yylval.scanFNum.kind = 2;
    break;
  }

  IEEE_set_round( oldRound );

  return F_NUMBER;
};

//--------------------------------------------------------------------------
// Name         F_HexNumber 
//
// 0[xX]{HEXFRACT_OR_INT}[pP][+-]?[0-9]+{FSUFFIX}?  
//--------------------------------------------------------------------------
static int F_HexNumber ( int leng, const char * text )
{
  IEEE_double_t res;
  extern const char * HexStringToDouble ( const char * text, IEEE_double_t * res );

  // skip over "0[xX]"

  if ( (text = HexStringToDouble( text + 2, &res )) == NULL)
  {
    ScannerError( "Hexadecimal foating point overflow" );
    return F_Number( 3, "0.0" );
  }

  switch (*text)
  {
  case 'f': case 'F':
    yylval.scanFNum.value.flt = IEEE_double_to_single( res );
    yylval.scanFNum.kind = 0;
    break;

  default:
    yylval.scanFNum.value.dbl = res;
    yylval.scanFNum.kind = 1;
    break;

  case 'l': case 'L':
    yylval.scanFNum.value.ldbl = res;
    yylval.scanFNum.kind = 2;
    break;
  }

  return F_NUMBER;
};

/* C whitespace */
/* Digits */
/* Universal character name */
/* escapes */
/* character character */
/* string character */
/* C identifier */
/* An identifier without universal characters */
/* integer suffix */
/* floating point suffix */
/* a fractional constant */
/* hex fractional constant */
/* exponent part */
/* binary exponent part */
#define COMMENT 1
#define LINE_COMMENT 2
#define PREPR_DIR 3
#define CHAR_STATE 4
#define STR_STATE 5
#define ID_STATE1 6
#define ID_STATE2 7

#define PLAIN_STR_STATE 8
#define PRAGMA_OP_END 9

#line 1417 "scan.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 806 "scan.l"


  CORD cord = NULL;
  int  prevState;  // PLAIN_STR_STATE returns to this one instead of INITIAL


#line 1574 "scan.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 319 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 725 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 812 "scan.l"
BEGIN( COMMENT );
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 813 "scan.l"
BEGIN( LINE_COMMENT );
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 814 "scan.l"
/* eat up whitespace */
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 815 "scan.l"
++yycurline;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 817 "scan.l"
cord = NULL; BEGIN(PREPR_DIR);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 819 "scan.l"
cord = NULL; BEGIN(ID_STATE1);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 821 "scan.l"
{
                  /* So here we go .. :-) We parse manually _Pragma(string) */
                  int c;
                  c = input();
                  if (c != '(')
                  {
                    ScannerError( "'(' expected after _Pragma" );
                    goto exit;
                  }

                  // Skip the blanks
                  while (isspace( c = input() ))
                    {}

                  if (c == 'l' || c == 'L')
                    c = input();

                  if (c != '"')
                  {
                    ScannerError( "A string expected after _Pragma(" );
                    goto exit;
                  }

                  prevState = PRAGMA_OP_END;
                  cord = NULL;
                  BEGIN( PLAIN_STR_STATE ); // parse the string

                exit:;
                }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 851 "scan.l"
{
                                 // Put the initial text in the cord without the '\\'
                                 cord = Cord_NewSegment( NULL, yyleng, yytext );
                                 BEGIN(ID_STATE1);
                               }   
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 857 "scan.l"
{
                                 STRING str = NewStringLen( yytext, yyleng ); 
                                 ASSERT( bWordsAdded );
                                 if (STRING_DATA(str)->token != 0)
                                   return SCANNER_SET_TC( STRING_DATA(str)->token );
                                 else
                                 {
                                   yylval.str = str;
                                   return IDENT;
                                 }
                               }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 869 "scan.l"
return Number( 8, yytext ); 
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 871 "scan.l"
{
                                 ScannerError( "Bad octal number" ); 
                                 return Number( 8, "0" );
                               }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 876 "scan.l"
return Number( 10, yytext ); 
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 878 "scan.l"
return Number( 16, yytext+2 );
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 879 "scan.l"
{
                                 ScannerError( "Invalid hex number" ); 
                                 return Number( 16, "0" );
                               }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 884 "scan.l"
return F_Number( yyleng, yytext );
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 886 "scan.l"
return F_Number( yyleng, yytext );
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 888 "scan.l"
{
                                 ScannerError( "Number expected after exponent" ); 
                                 return F_Number( 3, "0.0" );
                               }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 893 "scan.l"
return F_HexNumber( yyleng, yytext );
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 894 "scan.l"
ScannerError( "Bad floating point constant" ); return F_NUMBER;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 895 "scan.l"
ScannerError( "Bad floating point constant" ); return F_NUMBER;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 896 "scan.l"
ScannerError( "Bad floating point constant" ); return F_NUMBER;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 898 "scan.l"
bWide = false; BEGIN( CHAR_STATE ); cord = NULL; 
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 899 "scan.l"
bWide = true;  BEGIN( CHAR_STATE ); cord = NULL; 
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 900 "scan.l"
bWide = false; BEGIN( STR_STATE ); cord = NULL; 
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 901 "scan.l"
bWide = true;  BEGIN( STR_STATE ); cord = NULL; 
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 903 "scan.l"
return *yytext;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 904 "scan.l"
return *yytext;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 905 "scan.l"
return *yytext;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 906 "scan.l"
return *yytext;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 907 "scan.l"
return *yytext;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 908 "scan.l"
return *yytext;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 909 "scan.l"
return *yytext;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 911 "scan.l"
return PTR;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 912 "scan.l"
return INC;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 913 "scan.l"
return DEC;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 915 "scan.l"
return *yytext;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 916 "scan.l"
return *yytext;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 917 "scan.l"
return *yytext;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 918 "scan.l"
return *yytext;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 919 "scan.l"
return *yytext;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 920 "scan.l"
return *yytext;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 921 "scan.l"
return *yytext;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 922 "scan.l"
return *yytext;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 924 "scan.l"
return SCANNER_SET_E( e_shl, SHIFT );
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 925 "scan.l"
return SCANNER_SET_E( e_shr, SHIFT );
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 927 "scan.l"
return SCANNER_SET_E( e_less, ARITHCOMPARE );
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 928 "scan.l"
return SCANNER_SET_E( e_greater, ARITHCOMPARE );
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 929 "scan.l"
return SCANNER_SET_E( e_le_eq, ARITHCOMPARE );
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 930 "scan.l"
return SCANNER_SET_E( e_gr_eq, ARITHCOMPARE );
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 932 "scan.l"
return SCANNER_SET_E( e_eq, EQCOMPARE );
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 933 "scan.l"
return SCANNER_SET_E( e_ne, EQCOMPARE );
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 935 "scan.l"
return *yytext;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 936 "scan.l"
return *yytext;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 937 "scan.l"
return LOG_AND;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 938 "scan.l"
return LOG_OR;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 939 "scan.l"
return *yytext;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 940 "scan.l"
return *yytext;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 941 "scan.l"
return *yytext;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 942 "scan.l"
return ELLIPSIS;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 943 "scan.l"
ScannerError( "'..' is invalid. Did you mean '...'?" ); return ELLIPSIS;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 944 "scan.l"
return *yytext;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 946 "scan.l"
return SCANNER_SET_E( e_asgn_mul, ASSIGN );
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 947 "scan.l"
return SCANNER_SET_E( e_asgn_div, ASSIGN );
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 948 "scan.l"
return SCANNER_SET_E( e_asgn_mod, ASSIGN );
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 949 "scan.l"
return SCANNER_SET_E( e_asgn_plus, ASSIGN );
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 950 "scan.l"
return SCANNER_SET_E( e_asgn_minus, ASSIGN );
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 951 "scan.l"
return SCANNER_SET_E( e_asgn_and, ASSIGN );
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 952 "scan.l"
return SCANNER_SET_E( e_asgn_or, ASSIGN );
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 953 "scan.l"
return SCANNER_SET_E( e_asgn_xor, ASSIGN );
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 954 "scan.l"
return SCANNER_SET_E( e_asgn_shl, ASSIGN );
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 955 "scan.l"
return SCANNER_SET_E( e_asgn_shr, ASSIGN );
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 957 "scan.l"
return *yytext;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 958 "scan.l"
return '[';
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 959 "scan.l"
return ']';
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 960 "scan.l"
return '{';
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 961 "scan.l"
return '}';
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 963 "scan.l"
ScannerError( "Bad character '\\x%02x'", *yytext );
	YY_BREAK

case 78:
YY_RULE_SETUP
#line 967 "scan.l"
{
                          BEGIN(INITIAL); 
                          return CharConst( true, cord );
                        }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 972 "scan.l"
cord = AppendText( cord, 1, yytext+1 );
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 973 "scan.l"
cord = AppendText( cord, 1, "\a" );
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 974 "scan.l"
cord = AppendText( cord, 1, "\b" );
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 975 "scan.l"
cord = AppendText( cord, 1, "\f" );
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 976 "scan.l"
cord = AppendText( cord, 1, "\n" );
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 977 "scan.l"
cord = AppendText( cord, 1, "\r" );
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 978 "scan.l"
cord = AppendText( cord, 1, "\t" );
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 979 "scan.l"
cord = AppendText( cord, 1, "\v" );
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 980 "scan.l"
cord = AppendText( cord, 1, "\x1b" ); // GNU C extension
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 981 "scan.l"
cord = OctalEscape( cord, yytext );
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 982 "scan.l"
cord = HexEscape( cord, yytext );
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 983 "scan.l"
cord = UniCharEscape( cord, yytext );
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 984 "scan.l"
ScannerError( "Ill-formed universal character" );
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 986 "scan.l"
++yycurline; // concat lines
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 987 "scan.l"
ScannerError( "Bad escape character" );
	YY_BREAK
case YY_STATE_EOF(CHAR_STATE):
#line 989 "scan.l"
{ 
                          ScannerError( "Unterminated character constant" ); 
                          BEGIN(INITIAL); 
                          return CharConst( false, cord );
                        } 
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 995 "scan.l"
{ 
                          ScannerError( "Unterminated character constant" ); 
                          ++yycurline; 
                          BEGIN(INITIAL); 
                          return CharConst( false, cord );
                        } 
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 1002 "scan.l"
cord = AppendText( cord, yyleng, yytext );
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 1003 "scan.l"
cord = AppendText( cord, 1, yytext ); ASSERT(0); // Shouldn't happen
	YY_BREAK


case 97:
YY_RULE_SETUP
#line 1007 "scan.l"
{
                          BEGIN(INITIAL); 
                          return StringConst( cord );
                        }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 1012 "scan.l"
cord = AppendText( cord, 1, yytext+1 );
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 1013 "scan.l"
cord = AppendText( cord, 1, "\a" );
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 1014 "scan.l"
cord = AppendText( cord, 1, "\b" );
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 1015 "scan.l"
cord = AppendText( cord, 1, "\f" );
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 1016 "scan.l"
cord = AppendText( cord, 1, "\n" );
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 1017 "scan.l"
cord = AppendText( cord, 1, "\r" );
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 1018 "scan.l"
cord = AppendText( cord, 1, "\t" );
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 1019 "scan.l"
cord = AppendText( cord, 1, "\v" );
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 1020 "scan.l"
cord = AppendText( cord, 1, "\x1b" ); // GNU C extension
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 1021 "scan.l"
cord = OctalEscape( cord, yytext );
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 1022 "scan.l"
cord = HexEscape( cord, yytext );
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 1023 "scan.l"
cord = UniCharEscape( cord, yytext );
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 1024 "scan.l"
ScannerError( "Ill-formed universal character" );
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 1026 "scan.l"
++yycurline; // concat lines
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 1027 "scan.l"
ScannerError( "Bad escape character" );
	YY_BREAK
case YY_STATE_EOF(STR_STATE):
#line 1029 "scan.l"
{ 
                          ScannerError( "Unterminated string constant" ); 
                          BEGIN(INITIAL); 
                          return StringConst( cord );
                        } 
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 1035 "scan.l"
{ 
                          ScannerError( "Unterminated string constant" ); 
                          ++yycurline; 
                          BEGIN(INITIAL); 
                          return StringConst( cord );
                        } 
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 1042 "scan.l"
cord = AppendText( cord, yyleng, yytext );
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 1043 "scan.l"
cord = AppendText( cord, 1, yytext ); ASSERT(0); // Shouldn't happen
	YY_BREAK


case 116:
YY_RULE_SETUP
#line 1047 "scan.l"
{
                          ValidateIdentUniChar( yytext );
                          cord = Cord_NewSegment( cord, yyleng, yytext );
                          BEGIN(ID_STATE2);
                        }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 1053 "scan.l"
ScannerError( "Ill-formed universal character" );BEGIN(ID_STATE2);
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 1055 "scan.l"
{
  												ScannerError( "Ill-formed universal character" );
                          yyless(1); // put back the character
													BEGIN(ID_STATE2); 
                        }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 1061 "scan.l"
{
                          ++yycurline;  
													ScannerError( "Ill-formed universal character" );
													BEGIN(INITIAL); 
                          
                          yylval.str = StringFromCord( cord );

													return IDENT;
                        }
	YY_BREAK


case 120:
YY_RULE_SETUP
#line 1073 "scan.l"
{ 
                          ValidateIdentUniChar( yytext+1 );
                          cord = Cord_NewSegment( cord, yyleng, yytext );
                        }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 1078 "scan.l"
ScannerError( "Ill-formed universal character" );
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 1079 "scan.l"
ScannerError( "Ill-formed universal character" );
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 1081 "scan.l"
cord = Cord_NewSegment( cord, yyleng, yytext );
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 1083 "scan.l"
{ 
                          BEGIN(INITIAL); 
                          
                          yylval.str = StringFromCord( cord );

													return IDENT;
                        }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 1091 "scan.l"
{ 
                          ++yycurline; 
													BEGIN(INITIAL); 
                          
                          yylval.str = StringFromCord( cord );

													return IDENT;
                        }
	YY_BREAK


case 126:
YY_RULE_SETUP
#line 1102 "scan.l"
BEGIN(prevState); 
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 1104 "scan.l"
cord = Cord_NewSegment( cord, 1, yytext+1 );
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 1105 "scan.l"
cord = Cord_NewSegment( cord, 1, "\a" );
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 1106 "scan.l"
cord = Cord_NewSegment( cord, 1, "\b" );
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 1107 "scan.l"
cord = Cord_NewSegment( cord, 1, "\f" );
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 1108 "scan.l"
cord = Cord_NewSegment( cord, 1, "\n" );
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 1109 "scan.l"
cord = Cord_NewSegment( cord, 1, "\r" );
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 1110 "scan.l"
cord = Cord_NewSegment( cord, 1, "\t" );
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 1111 "scan.l"
cord = Cord_NewSegment( cord, 1, "\v" );
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 1112 "scan.l"
cord = Cord_NewSegment( cord, 1, "\x1b" ); // GNU C extension
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 1114 "scan.l"
{
                          unsigned value;

                          if ( (value = strtol( yytext+1, NULL, 8 )) > UCHAR_MAX)
                            ScannerError( "Value %u too big for a character", value );
                          else
                          {
                            char c = (char)value;
                            cord = Cord_NewSegment( cord, 1, &c );
                          }
                        }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 1126 "scan.l"
{
                          unsigned value;

                          // The number of hex digits must not be more than
                          // what is necessary to fill a char. No need to check 
                          // further in that case (strtol is a bitch in that respect)
                          //
                          if (yyleng > (CHAR_BIT+3)/4+2 ||
                              (value = strtol( yytext+2, NULL, 16 )) > UCHAR_MAX)
                            ScannerError( "Value %u too big for a character", value );
                          else
                          {
                            char c = (char)value;
                            cord = Cord_NewSegment( cord, 1, &c );
                          }
                        }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 1143 "scan.l"
++yycurline; // concat lines
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 1144 "scan.l"
ScannerError( "Bad escape character" );
	YY_BREAK
case YY_STATE_EOF(PLAIN_STR_STATE):
#line 1146 "scan.l"
{ 
                          ScannerError( "Unterminated string constant" ); 
                          BEGIN(prevState); 
                        } 
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 1151 "scan.l"
{ 
                          ScannerError( "Unterminated string constant" ); 
                          ++yycurline;
                          BEGIN(prevState); 
                        } 
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 1157 "scan.l"
cord = Cord_NewSegment( cord, yyleng, yytext );
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 1158 "scan.l"
cord = Cord_NewSegment( cord, 1, yytext ); ASSERT(0); // Shouldn't happen
	YY_BREAK


case 143:
YY_RULE_SETUP
#line 1162 "scan.l"
// ignore blanks
	YY_BREAK
case YY_STATE_EOF(PRAGMA_OP_END):
#line 1164 "scan.l"
{
                          ScannerError( "')' expected after _Pragma(string" ); 

                          BEGIN(INITIAL); 
                          // Simulate a #pragma ....
                          ScannerPrepr( Cord_AppendCord( 
                                          Cord_NewSegment( NULL, 7, "pragma " ),
                                          cord ) );
                          return 0;
                        }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 1174 "scan.l"
{
                          if (*yytext != ')')
                          {
                            ScannerError( "')' expected after _Pragma(string" ); 
                            yyless(0);
                          }

                          BEGIN(INITIAL); 
                          // Simulate a #pragma ....
                          ScannerPrepr( Cord_AppendCord( 
                                          Cord_NewSegment( NULL, 7, "pragma " ),
                                          cord ) );
                        }  
	YY_BREAK


case YY_STATE_EOF(PREPR_DIR):
#line 1190 "scan.l"
BEGIN(INITIAL); ScannerPrepr( cord ); return 0;
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 1191 "scan.l"
++yycurline; BEGIN(INITIAL); ScannerPrepr( cord );
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 1193 "scan.l"
// concat lines 
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 1194 "scan.l"
cord = Cord_NewSegment( cord, yyleng, yytext );
	YY_BREAK


case YY_STATE_EOF(COMMENT):
#line 1198 "scan.l"
ScannerError( "Comment not closed" ); BEGIN(INITIAL); return 0;
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 1199 "scan.l"
BEGIN(INITIAL);
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 1200 "scan.l"
++yycurline;
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 1201 "scan.l"

	YY_BREAK


case YY_STATE_EOF(LINE_COMMENT):
#line 1205 "scan.l"
BEGIN(INITIAL); return 0;
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 1206 "scan.l"
// concat lines 
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 1207 "scan.l"
++yycurline; BEGIN(INITIAL); 
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 1208 "scan.l"

	YY_BREAK

case 154:
YY_RULE_SETUP
#line 1212 "scan.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 2634 "scan.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ID_STATE1):
case YY_STATE_EOF(ID_STATE2):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 319 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 319 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 318);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 1212 "scan.l"


//--------------------------------------------------------------------------
// Name         Scanner_Init 
//
// 
//--------------------------------------------------------------------------
void Scanner_Init ()
{
  InitReservedWords();
  yycurline = 1;
};

//--------------------------------------------------------------------------
// Name         ScannerPrepr 
//
// 
//--------------------------------------------------------------------------
void ScannerPrepr ( CORD cord )
{
  extern int Prepr_Parse ( CORD cord );

  Prepr_Parse( cord );
};

#ifdef TEST_YYLEX

void ScannerPrepr ( CORD cord )
{
  extern int Prepr_Parse ( CORD cord );

  // Just for now
  if (cord)
    printf( "# %s\n", C_STR( StringFromCord( cord ) ) );

  Prepr_Parse( cord );
};

#include <stdarg.h>
void ScannerError ( const char * str, ... )
{
  va_list ap;
  va_start( ap, str );

  fprintf( stderr, "error line %d:", yycurline );
  vfprintf( stderr, str, ap );
  printf( "\n" );

  va_end( ap );
};

void ScannerWarning ( const char * str, ... )
{
  va_list ap;
  va_start( ap, str );

  fprintf( stderr, "warning line %d:", yycurline );
  vfprintf( stderr, str, ap );
  printf( "\n" );

  va_end( ap );
};

YYSTYPE yylval;

int main ( void )
{
  int c;

  Strings_Init();
  TConf_Init();
  Scanner_Init();

  while (c = yylex())
  {
    printf( "%s = %d ", yytext, c );
    switch (c)
    {
      case IDENT: 
        printf( " %p=%s", yylval.str, C_STR(yylval.str) ); 
        break;

      case CHAR_CONST: 
      case LCHAR_CONST: 
      case STRING_CONST:
      case LSTRING_CONST:
        if (c == LCHAR_CONST || c == LSTRING_CONST)
          printf( "L " );
        {
          CORD cord;
          for ( cord = yylval.cord; cord != NULL; cord = cord->pNext )
          {
            int i;
            for ( i = 0; i < cord->segLen; ++i )
            {
              TARGET_CHAR * t = (TARGET_CHAR *)cord->u.data + i;
            }
          }
        }
        break;
    }

    printf( "\n" );
  }

  Strings_Done();
  return 0;
};

#endif // TEST_YYLEX
